version = 0.1

[dev.global.parameters]
stack_name              = "grocery-scanner-dev"
template_file           = ".aws-sam/build/template.yaml"
resolve_s3              = true
s3_prefix               = "grocery-scanner"
region                  = "eu-west-2"
capabilities            = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset       = false
fail_on_empty_changeset = false

[dev.deploy.parameters]
parameter_overrides     = ["Environment=dev", "AlertEmail=your@gmail.com", "CognitoCallbackUrl=https://d34shldjctzphb.cloudfront.net"]
tags                    = "Project=GroceryScanner Environment=dev"

[dev.build.parameters]
template_file           = "infrastructure/template.yaml"

[prod.global.parameters]
stack_name              = "grocery-scanner-prod"
template_file           = ".aws-sam/build/template.yaml"
resolve_s3              = true
s3_prefix               = "grocery-scanner"
region                  = "eu-west-2"
capabilities            = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset       = true
fail_on_empty_changeset = false

[prod.deploy.parameters]
parameter_overrides     = ["Environment=prod", "AlertEmail=your@gmail.com", "CognitoCallbackUrl=https://dmsq3wtut3507.cloudfront.net", "GoogleSheetId=1Ixuyc4jyTt9AXV5ql0zI-2T1DxY4VPaLq08e4HkRYpE"]
tags                    = "Project=GroceryScanner Environment=prod"

[prod.build.parameters]
template_file           = "infrastructure/template.yaml"